import type { Metadata } from "next";
import "./globals.css";
import { GoogleOAuthProvider } from "@react-oauth/google";

export const metadata: Metadata = {
  title: "Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,management
}: Readonly<{
  children: React.ReactNode,management:React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <GoogleOAuthProvider clientId='677636272319-pm4dg5t7aj6f40achecapj0e4g196503.apps.googleusercontent.com'>
        <div>{children}</div>
        <div>{management}</div>
        </GoogleOAuthProvider>
      </body>
    </html>
  );
}
